### ISSUE TITLE
Thème Bosco

### ISSUE THREAD

**Issue by Gaetanbrl** [geosas/bosco#2]
## Cas d'usage

En tant qu'utilisateur Bosco
Je souhaite voir un thème spécifique ergonomique
Afin d'identifier rapidement la carte et la partager au grand public

## Tâches

- [x] Création d'un thème mviewer spécifique

**Comment by Gaetanbrl** [comment]
@llonguev et @hsquividant avez-vous une charte graphique pour le thème ? L'idée étant que @Agath21 reparte de couleurs existantes pour réaliser un thème en lien avec les couleurs Bosco existantes (si existantes).

Exemple de possibilité (proposée par @Agath21) : 

- Reprendre les couleurs et la typo (`font-family: Montserrat, serif;`) du site du SCO :

https://www.spaceclimateobservatory.org/fr/projects

![image](https://github.com/geosas/bosco/assets/16317988/a5ac25a6-83ac-4f66-bcd0-2830e84c9688)

**Comment by Gaetanbrl** [comment]
Nous attendons un retour de @llonguev pour valider que nous pouvons partir sur ce thème si ce choix convient.

**Comment by Gaetanbrl** [comment]
Vu avec @llonguev ce jour : 

- On repart du projet SCO pour le thème comme proposé dans les commentaires précédents
- Utiliser un logo : ne pas mettre de logo et mettre un titre qui convient (proposition @Agath21)
- Masquer le volet "Thématiques" contenant les couches
- Dans la légende, interdire la suppression

**Comment by Agath21** [comment]
## Application 

- [x] Thème avec univers visuel du SCO 
- [x] Pas de logo 
- [x] CRéation d'un favicon simple
- [x] Revoir le titre de l'app 
- [x] Masquer le volet "Thématiques" contenant les couches
- [x] Dans la légende, interdire la suppression des couches 
- [x] Desactiver la couche Chroniques de l'humidité des Parcelles 
- [x] Masquer la couche Contour des parcelles RPG dans la légende

**Comment by Agath21** [comment]
>  Masquer la couche Contour des parcelles RPG dans la légende


En activant le paramètre mviewer `showintoc = "false" `sur cette couche, l'interrogation ne fonctionne plus. 
J'ai donc trouver une alternative en .css en attendant de se pencher sur le bug : 
```
.list-group-item.mv-layer-details[data-layerid=rpg_bosco] {
   display: none;
}
```

**Comment by Agath21** [comment]
## Interrogation 

Adapter le style du template avec le thème 
Revoir les intitulés des onglets : "Chronologie" / "Synthèse annuelle"

### Chronologie : 

- [x] Ajouter un titre
- [ ] Revoir les labels en français
- [x] Revoir la couleur de la line (bleu SCO) 
- [x] Corriger les labels de xAxis "year"
- [x] Ajouter un message d'aide à la navigation 

### Synthèse annuelle : 

- [x] Revoir le titre du graphique + sous-titre
- [x] Revoir le style des chiffres clés
- [x] Mettre les mois en français
- [x] Modification des labels des courbes :
- Médiane ➔ Normale de saison (2027-2022)
- Quartile 25 ➔ Supprimer la légende pour cette courbe
- Quartile 75 ➔ Supprimer la légende pour cette courbe
- Médianne année ➔ Année sélectionnée

- [x] Revoir la représentation des lignes :
- Médiane ➔ Normale de saison (2027-2022) en bleu ciel
- Quartile 25 + 75➔ créer une aire colorée en transparence
- Médianne année ➔ Année sélectionnée en bleu SCO (idem graph chronologie pour la cohérence)

**Comment by Agath21** [comment]
@hsquividant , afin d'améliorer la lisibilité de la couche "Humidité des sols", peux-tu supprimer le fond gris du style de la couche `rpg_bosco` au sein du geoserver et laisser seulement le contour ?

Merci beaucoup :)

**Comment by Agath21** [comment]
> Quartile 25 + 75➔ créer une aire colorée en transparence

![image](https://github.com/geosas/bosco/assets/22764056/302ac8c3-2e31-4235-931d-6a8f9d4e32e1)


Pour créer une série `type: 'arearange'` (Q25 et Q75), il faut importer un module supplémentaire de la lib highcharts : https://code.highcharts.com/highcharts-more.js 

Comme pour la lib de base, je l'ai ajouté comme ceci : 
- Ajout d'une extension dans le `default.xml `
- Ajout du fichier js dans `lib/highcharts`

Toutefois, je n'ai pas réussi à la charger ... Alors que en ajoutant l'url vers le js, cela fonctionne.

Problème à voir avec @Gaetanbrl à son retour

**Comment by hsquividant** [comment]
> @hsquividant , afin d'améliorer la lisibilité de la couche "Humidité des sols", peux-tu supprimer le fond gris du style de la couche `rpg_bosco` au sein du geoserver et laisser seulement le contour ?
> 
> Merci beaucoup :)

@agath21, c'est fait

**Comment by Agath21** [comment]
> > @hsquividant , afin d'améliorer la lisibilité de la couche "Humidité des sols", peux-tu supprimer le fond gris du style de la couche `rpg_bosco` au sein du geoserver et laisser seulement le contour ?
> > Merci beaucoup :)
> 
> @Agath21, c'est fait

Effectivement, c'est visible pour moi ! merci !

**Comment by Gaetanbrl** [comment]
Sujet couvert, je clos. Merci à tous.
