### ISSUE TITLE
Visualisation des données SensorThings

### ISSUE THREAD

**Issue by Gaetanbrl** [geosas/bosco#5]
## Cas d'usage

> En tant qu'utilisateur Bosco
> Je souhaite voir les données RPG dans mviewer
> Afin de les consulter en mode SensorThings

## Présentation

La couche rpg_bosco est disponible sous forme de WMS. 
https://geosas.fr/geoserver/bosco/ows?SERVICE=WMS&REQUEST=GetCapabilities

Cette couche représente le RPG mis à jour par l'INRAE :
https://geosas.fr/mapfishapp/map/a2beef525410925b4b3881b213ab971d
 
Elle contient un champ thingsUrl qui permettra d'appeler les données type SensorThings pour une parcelle : 
![rpg_SensorThingsUrl](https://github.com/geosas/bosco/assets/1828333/ac7c4b21-7ea9-4cfe-8023-a0fb183f19ed)

## Description fonctionnelle

Lorsque l'utilisateur clique sur une parcelle, c'est l'outil sensorThings mviewer qui est appelé avec le customControl adéquate.
La nouveauté est que ce n'est pas une couche type sensorThings qui est cliquée mais un WMS.

## Description technique

Voici l'enchainement à réaliser : 

1. Lors du clique sur une parcelle du RPG, l'outil devra faire un GFI :

https://geosas.fr/geoserver/bosco/ows?SERVICE=WMS&LAYERS=rpg_bosco&QUERY_LAYERS=rpg_bosco&STYLES=&SERVICE=WMS&VERSION=1.3.0&REQUEST=GetFeatureInfo&EXCEPTIONS=XML&BBOX=-243282.988701,6097779.041519,-212459.757045,6109970.74753&FEATURE_COUNT=1000&HEIGHT=638&WIDTH=1613&FORMAT=image/png&INFO_FORMAT=application/json&CRS=EPSG:3857&I=725&J=469

2. Lecture des attributs et requête du Things :
https://frost.geosas.fr/bosco/v1.0/Things(41104)

3. Récupération de l’URL DataStreams et requête DataStreams :
https://frost.geosas.fr/bosco/v1.0/Things(41104)/Datastreams

4. Récupération de l’URL des observations et requête des Observations :
https://frost.geosas.fr/bosco/v1.0/Datastreams(41104)/Observations

Pour cette réalisation, un champ qui pourra être nommé `sensorThingsField` pourra être rajouté dans mviewer afin de faire le lien entre un WMS et le champ qui contient l'URL du things dans ce flux WMS.
Ce sera alors la valeur du champ correspondant au `sensorThingsField ` qui sera utilisé pour déclencher l'outil sensorThings dans mviewer.

## Tâches

- [x] Reprise du XML existant
- [x] Ajouter un champ dans le RPG qui affiche l'ID things
- [x] Validation PR sensorThings
- [ ] Ajout du paramètre `sensorThingsField` dans mviewer et issue associée
- [ ] Ajout du code dans mviewer pour détecter le champ et afficher l'outil de sensorthings
- [ ] Création d'un template

**Comment by hsquividant** [comment]
Il faut maintenant utiliser la nouvelle couche bosco_rpg qui contient un champ **_thingsUrl_** et un champ _**Id**_ correspondant à l'ID de la Things. 
Les URL de la présentation et de la description technique ont été mis à jour.

**Comment by Gaetanbrl** [comment]
ok vu @hsquividant merci

![image](https://github.com/geosas/bosco/assets/16317988/ca0e8f77-3f45-4472-a71b-a5a16df15892)

https://geosas.fr/geoserver/bosco/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=rpg_bosco&maxFeatures=50&outputFormat=application%2Fjson

**Comment by Gaetanbrl** [comment]
A notre demande, les champs service_url et things_id ont été rajoutés par @t-loree afin de pouvoir capter l'ID du thing et le service plus facilement en vue de réutiliser l'ID du thing dans un autre service (e.g stat) :

```
"properties": {
    "idp": 6,
    "name": "Parcel 6",
    "description": "Parcel from Land Parcel Identification System (LPIS) year 2017 and 2019 n° 6",
    "thingsUrl": "https://frost.geosas.fr/bosco/v1.0/Things(3)",
    "thing_id": 3,
    "service_url": "https://frost.geosas.fr/bosco/v1.0/"
}
```

**Comment by Gaetanbrl** [comment]
Ok validé, PR à faire du Fork vers /bosco.
