### ISSUE TITLE
Page d'accueil Bosco

### ISSUE THREAD

**Issue by Gaetanbrl** [geosas/bosco#6]
## Description

En tant qu'utilisateur,
Je souhaite disposer d'une page qui m'affiche du contenu (image, textes,...)
Afin d'en savoir plus sur le projet Bosco, les liens utiles et les partenaires.

## Exemple de réalisation passée : 

https://geosas.fr/simfen/

![image](https://github.com/geosas/bosco/assets/16317988/94872ea1-e1f0-426b-b4ca-ebd1f66ead4a)
![image](https://github.com/geosas/bosco/assets/16317988/ed7844c5-6f37-48e1-88d4-1ed36c958b1c)

## Détail

La page d'acceuil (page Home du mviewer) devra contenir:
- La vidéo bosco https://vimeo.com/868221765/aef55baba9
- Du texte fourni par l'équipe projet (@hsquividant ou Laurent L.)
- Des images fournies par l'équipe projet
- Du contenu divers

L'ensemble des éléments sont à spécifier par l'équipe projet Bosco dans cette issue (en commentaire).

## Tâches 

- [ ] Fournir le contenu à JDev
- [ ] Création d'une page d'accueil avec la vidéo / liens Bosco

**Comment by hsquividant** [comment]
2 documents à réutiliser dans cette page d'accueil :

- La page de présentation du projet BOSCO sur le site du SCO : https://www.spaceclimateobservatory.org/fr/bosco

- La Méthode BOSCO décrite dans le PDF : https://geosas.fr/metadata/pdf/Livrable_TED_Bosco_Mars2022_Bretagne_INRAE_Baghdadi.pdf

**Comment by hsquividant** [comment]
Une première proposition 

1. Onglet Accueil / Bienvenue --> texte d’accroche de la page de présentation à éventuellement orienter d'avantage utilisateur.  
2. ~Onglet Mode d'emploi --> on pourrait reprendre le principe de vidéos très courtes qui expliquent les différents méthodes de consultations comme celles faites par @t-loree fin 2023~
3. Onglet Méthode --> intégrer les éléments du PDF
4. Onglet Biblio / Références -> intégrer la biblio de la page 8 du PDF
5. Onglet Partenaires -> reprendre les logos du bas de la page de présentation   

> Les éléments barrés ne sont pas retenus dans la proposition finale

**Comment by Agath21** [comment]
Pour l'onglet accueil (issue du site SCO) : 

> Le projet BOSCO propose de co-construire un service d’estimation de teneur en eau sur le territoire breton à très haute résolution spatiale et temporelle, pertinente pour la gestion agricole et des ressources en eau. Ce service intègre des outils diagnostique et des produits dérivés (teneur en eau sur l’épaisseur racinaire, estimation de la recharge) pour l’appui aux politiques publiques.

et vidéo du projet

**Comment by Gaetanbrl** [comment]
En complément dans la page d'accueil il est proposé : 

- Pour le texte d'accueil -> Voir le commentaire précédent d'@Agath21
- Dans l'onglet méthode, fournir une synthèse et d'ajouter en dessous une liseuse du PDF ([voir cet exemple](https://fr.w3docs.com/tools/code-editor/1805)) ou le lien vers PDF
- Dans l'onglet biblio. Référence, reprendre les références du PDF

**Comment by Gaetanbrl** [comment]
Nous attendons la validation de @llonguev pour commencer la réalisation de la page d'accueil.

**Comment by Gaetanbrl** [comment]
Vu avec @llonguev :

- Onglet Accueil : 

Reprendre ce texte : 

> Le projet BOSCO propose de co-construire un service d’estimation de teneur en eau sur le territoire breton à très haute résolution spatiale et temporelle, pertinente pour la gestion agricole et des ressources en eau. Ce service intègre des outils diagnostique et des produits dérivés (teneur en eau sur l’épaisseur racinaire, estimation de la recharge) pour l’appui aux politiques publiques.

Ajouter en dessous la vidéo :

https://www.youtube.com/watch?time_continue=104&v=Jz135UeLfsY&embeds_referring_euri=https%3A%2F%2Fwww.spaceclimateobservatory.org%2F

Ajouter un lien vers la page du projet :

https://www.spaceclimateobservatory.org/fr/bosco

- Dans l'onglet méthode :

Reprendre la partie 1 et la partie 3.1 du PDF (copier/coller) pour cette méthode avec un lien vers le PDF.
Intégrer égalment la figure 2 :
![image](https://github.com/geosas/bosco/assets/16317988/06d7b779-d3c1-486f-a5f3-a67e34e3426e)


- Dans l'onglet biblio. Référence, reprendre les références du PDF (copier / coller)

- Pour les partenaires, reprendre ceux de la vidéo et les regrouper de la même manière  : 

**mettre les financeurs en plus qui ne sont pas présents dans la vidéo : en premier le SCO et ensuite le CNES**

![image](https://github.com/geosas/bosco/assets/16317988/e7cee758-701c-4823-8289-b7b1b980c3b5)

**Comment by Agath21** [comment]
## Page d'accueil 

- [x] Thème pour la page d'accueil


Accueil
- [x] Créer l'onglet
- [x] Ajouter le contenu + vidéo

Méthode
- [x] Créer l'onglet
- [x] Ajouter le contenu

Bibliographie
- [x] Créer l'onglet
- [x] Ajouter le contenu

Partenaires
- [x] Créer l'onglet
- [x] Ajouter le contenu + logo

**Comment by Gaetanbrl** [comment]
Sujet couvert. Je clos. Merci à tous.
